### ISSUE TITLE
Error when deploying 2 rancher/server containers in v0.8.0-rc4

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1534]
Launched 2 rancher/server containers on a t2.micro instance.

``` 
docker ps
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xa6b6f7 m=0

goroutine 0 [idle]:

goroutine 1 [running]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82001c770 sp=0xc82001c768
runtime.main()
    /usr/local/go/src/runtime/proc.go:126 +0x62 fp=0xc82001c7c0 sp=0xc82001c770
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82001c7c8 sp=0xc82001c7c0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

rax    0x0
rbx    0x1374fc8
rcx    0xa6b6f7
rdx    0x6
rdi    0x2ee8
rsi    0x2ee8
rbp    0xeed7de
rsp    0x7ffe896ce808
r8     0xa
r9     0x2e51880
r10    0x8
r11    0x206
r12    0x2e53c10
r13    0xeba544
r14    0x0
r15    0x8
rip    0xa6b6f7
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

**Comment by SvenDowideit** [comment]
I wonder if we're just running out of memory (we haven't removed anything in 0.8, and we've converted lots of previously ephemeral script code into go code built into ros)

**Comment by SvenDowideit** [comment]
@deniseschannon so you're running rancher agent, ecs agent, and 2 other containers?

what where they?

**Comment by ibuildthecloud** [comment]
@deniseschannon 2 rancher/server won't fit in a t2.micro.  You will run out of memory.

**Comment by SvenDowideit** [comment]
oh?! you mean literally? gosh

**Comment by SvenDowideit** [comment]
user docker or system docker?

**Comment by SvenDowideit** [comment]
moving this to 0.9 - its not a bug, but it would be nice if we can have less crashy looking errors when running out of memory, or whatever resource failure this is.

**Comment by chriswayg** [comment]
**Is the error below also due to being out of memory?** Aren't there better ways to handle low memory situations for RancherOS (v1.2.0)? 

> docker: Error response from daemon: grpc: the connection is unavailable.
> 
> [rancher@mail mailcow-dockerized]$ system-docker ps
> runtime/cgo: pthread_create failed: Resource temporarily unavailable
> SIGABRT: abort
> PC=0xd85078 m=0 sigcode=18446744073709551610
> goroutine 0 [idle]:
> goroutine 1 [running]:
> runtime.systemstack_switch()
> 	/usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc420022788 sp=0xc420022780
> runtime.main()
> 	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200227e0 sp=0xc420022788
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200227e8 sp=0xc4200227e0
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
> 
> rax    0x0
> rbx    0x17d33f8
> rcx    0xd85078
> ...

After restart , as the same containers started automatically...

`$ docker ps`
`   Segmentation fault`

Increasing the DigitalOcean RancherOS droplet's memory to 2GB fixed the problem.
